import { Course } from './firestore-schemas';

// Sample courses used as fallback data when Firestore is empty or unavailable
export const sampleCourses: Course[] = [
    // ─── Web Development ───
    {
        id: 'sample-1',
        title: 'React.js Masterclass',
        description: 'Master React from the ground up. Build production-grade SPAs with hooks, context, Redux, and React Router. Includes real-world projects like a social media dashboard and an e-commerce storefront with full state management.',
        category: 'Web Development',
        level: 'intermediate',
        price: 199,
        instructor: 'inst-1',
        instructorName: 'Alex Rivera',
        thumbnail: '',
        rating: 4.8,
        reviewCount: 342,
        enrollmentCount: 4200,
        duration: 1920, // 32 hours
        lessons: [
            { id: 'l1-1', courseId: 'sample-1', title: 'Introduction to React', description: 'Understanding the core concepts', videoUrl: '', duration: 45, order: 1 },
            { id: 'l1-2', courseId: 'sample-1', title: 'JSX and Components', description: 'Building reusable components', videoUrl: '', duration: 60, order: 2 },
            { id: 'l1-3', courseId: 'sample-1', title: 'State and Props', description: 'Managing component data', videoUrl: '', duration: 55, order: 3 },
            { id: 'l1-4', courseId: 'sample-1', title: 'Hooks Deep Dive', description: 'useState, useEffect, and custom hooks', videoUrl: '', duration: 70, order: 4 },
            { id: 'l1-5', courseId: 'sample-1', title: 'Context API & Redux', description: 'Global state management', videoUrl: '', duration: 65, order: 5 },
        ],
        createdAt: new Date('2024-01-15'),
        updatedAt: new Date('2024-06-20'),
    },
    {
        id: 'sample-2',
        title: 'Next.js Advanced: Full-Stack Apps',
        description: 'Take your Next.js skills to the next level. Learn server components, app router, API routes, middleware, ISR, and deploy production apps on Vercel. Build a complete SaaS application with authentication and payments.',
        category: 'Web Development',
        level: 'advanced',
        price: 299,
        instructor: 'inst-2',
        instructorName: 'Sarah Chen',
        thumbnail: '',
        rating: 4.9,
        reviewCount: 218,
        enrollmentCount: 3100,
        duration: 2400, // 40 hours
        lessons: [
            { id: 'l2-1', courseId: 'sample-2', title: 'App Router Architecture', description: 'Layouts, pages, and loading states', videoUrl: '', duration: 50, order: 1 },
            { id: 'l2-2', courseId: 'sample-2', title: 'Server Components', description: 'Streaming and suspense patterns', videoUrl: '', duration: 65, order: 2 },
            { id: 'l2-3', courseId: 'sample-2', title: 'API Routes & Middleware', description: 'Building backend APIs', videoUrl: '', duration: 55, order: 3 },
            { id: 'l2-4', courseId: 'sample-2', title: 'Authentication with NextAuth', description: 'OAuth, JWT, and sessions', videoUrl: '', duration: 70, order: 4 },
            { id: 'l2-5', courseId: 'sample-2', title: 'Deployment & Performance', description: 'Vercel, caching, and optimization', videoUrl: '', duration: 45, order: 5 },
        ],
        createdAt: new Date('2024-02-10'),
        updatedAt: new Date('2024-07-15'),
    },
    {
        id: 'sample-3',
        title: 'HTML & CSS for Beginners',
        description: 'Start your web development journey with HTML5 and CSS3. Learn semantic markup, responsive design with Flexbox and Grid, animations, and build five beautiful websites from scratch. No prior experience needed.',
        category: 'Web Development',
        level: 'beginner',
        price: 99,
        instructor: 'inst-3',
        instructorName: 'Marcus Johnson',
        thumbnail: '',
        rating: 4.7,
        reviewCount: 890,
        enrollmentCount: 5000,
        duration: 960, // 16 hours
        lessons: [
            { id: 'l3-1', courseId: 'sample-3', title: 'HTML Fundamentals', description: 'Tags, elements, and structure', videoUrl: '', duration: 40, order: 1 },
            { id: 'l3-2', courseId: 'sample-3', title: 'CSS Styling Basics', description: 'Selectors, properties, and box model', videoUrl: '', duration: 50, order: 2 },
            { id: 'l3-3', courseId: 'sample-3', title: 'Flexbox Layout', description: 'Flexible responsive layouts', videoUrl: '', duration: 45, order: 3 },
            { id: 'l3-4', courseId: 'sample-3', title: 'CSS Grid', description: 'Two-dimensional layouts', videoUrl: '', duration: 45, order: 4 },
        ],
        createdAt: new Date('2023-11-01'),
        updatedAt: new Date('2024-05-10'),
    },
    {
        id: 'sample-4',
        title: 'Node.js & Express Backend Development',
        description: 'Build scalable backend services with Node.js and Express. Cover RESTful APIs, authentication, database integration with MongoDB, error handling, testing, and deployment. Perfect for frontend devs going full-stack.',
        category: 'Web Development',
        level: 'intermediate',
        price: 199,
        instructor: 'inst-4',
        instructorName: 'David Park',
        thumbnail: '',
        rating: 4.6,
        reviewCount: 265,
        enrollmentCount: 2800,
        duration: 1800, // 30 hours
        lessons: [
            { id: 'l4-1', courseId: 'sample-4', title: 'Node.js Fundamentals', description: 'Event loop, modules, and streams', videoUrl: '', duration: 55, order: 1 },
            { id: 'l4-2', courseId: 'sample-4', title: 'Express Framework', description: 'Routing, middleware, and templating', videoUrl: '', duration: 50, order: 2 },
            { id: 'l4-3', courseId: 'sample-4', title: 'RESTful API Design', description: 'CRUD operations and best practices', videoUrl: '', duration: 60, order: 3 },
            { id: 'l4-4', courseId: 'sample-4', title: 'MongoDB Integration', description: 'Mongoose, schemas, and queries', videoUrl: '', duration: 55, order: 4 },
        ],
        createdAt: new Date('2024-03-05'),
        updatedAt: new Date('2024-08-12'),
    },

    // ─── Design ───
    {
        id: 'sample-5',
        title: 'UI/UX Design Bootcamp',
        description: 'A comprehensive bootcamp covering user research, wireframing, prototyping, and visual design. Learn design thinking methodology, usability principles, and create a professional portfolio of three complete case studies.',
        category: 'Design',
        level: 'beginner',
        price: 199,
        instructor: 'inst-5',
        instructorName: 'Emma Wilson',
        thumbnail: '',
        rating: 4.8,
        reviewCount: 412,
        enrollmentCount: 3600,
        duration: 2160, // 36 hours
        lessons: [
            { id: 'l5-1', courseId: 'sample-5', title: 'Design Thinking Process', description: 'Empathize, define, ideate, prototype, test', videoUrl: '', duration: 50, order: 1 },
            { id: 'l5-2', courseId: 'sample-5', title: 'User Research Methods', description: 'Interviews, surveys, and personas', videoUrl: '', duration: 55, order: 2 },
            { id: 'l5-3', courseId: 'sample-5', title: 'Wireframing & Prototyping', description: 'Low to high fidelity designs', videoUrl: '', duration: 60, order: 3 },
            { id: 'l5-4', courseId: 'sample-5', title: 'Visual Design Principles', description: 'Color, typography, and layout', videoUrl: '', duration: 50, order: 4 },
        ],
        createdAt: new Date('2024-01-20'),
        updatedAt: new Date('2024-06-25'),
    },
    {
        id: 'sample-6',
        title: 'Figma Complete Guide',
        description: 'Master Figma from basics to advanced features. Learn auto-layout, components, variants, design tokens, prototyping with interactions, and team collaboration. Build a complete design system and mobile app mockup.',
        category: 'Design',
        level: 'intermediate',
        price: 149,
        instructor: 'inst-6',
        instructorName: 'Lisa Chang',
        thumbnail: '',
        rating: 4.7,
        reviewCount: 298,
        enrollmentCount: 2400,
        duration: 1440, // 24 hours
        lessons: [
            { id: 'l6-1', courseId: 'sample-6', title: 'Figma Interface Overview', description: 'Tools, panels, and shortcuts', videoUrl: '', duration: 35, order: 1 },
            { id: 'l6-2', courseId: 'sample-6', title: 'Components & Variants', description: 'Reusable design elements', videoUrl: '', duration: 55, order: 2 },
            { id: 'l6-3', courseId: 'sample-6', title: 'Auto Layout Mastery', description: 'Responsive component design', videoUrl: '', duration: 50, order: 3 },
            { id: 'l6-4', courseId: 'sample-6', title: 'Prototyping & Interactions', description: 'Animations and user flows', videoUrl: '', duration: 45, order: 4 },
        ],
        createdAt: new Date('2024-02-28'),
        updatedAt: new Date('2024-07-10'),
    },
    {
        id: 'sample-7',
        title: 'Motion Design with After Effects',
        description: 'Create stunning motion graphics and visual effects with Adobe After Effects. Learn keyframe animation, expressions, shape layers, compositing, and export for web and social media. Bring your designs to life.',
        category: 'Design',
        level: 'advanced',
        price: 249,
        instructor: 'inst-7',
        instructorName: 'Ryan Foster',
        thumbnail: '',
        rating: 4.6,
        reviewCount: 156,
        enrollmentCount: 1200,
        duration: 1680, // 28 hours
        lessons: [
            { id: 'l7-1', courseId: 'sample-7', title: 'After Effects Essentials', description: 'Interface, timeline, and keyframes', videoUrl: '', duration: 50, order: 1 },
            { id: 'l7-2', courseId: 'sample-7', title: 'Shape Layer Animation', description: 'Creating vector animations', videoUrl: '', duration: 60, order: 2 },
            { id: 'l7-3', courseId: 'sample-7', title: 'Expressions & Scripts', description: 'Automating animations with code', videoUrl: '', duration: 55, order: 3 },
        ],
        createdAt: new Date('2024-04-15'),
        updatedAt: new Date('2024-08-30'),
    },

    // ─── Business ───
    {
        id: 'sample-8',
        title: 'Startup Fundamentals',
        description: 'Learn how to turn your idea into a viable business. Covers market validation, business model canvas, MVP development, fundraising, pitching to investors, and scaling strategies. Includes real founder interviews.',
        category: 'Business',
        level: 'beginner',
        price: 149,
        instructor: 'inst-8',
        instructorName: 'Michael Torres',
        thumbnail: '',
        rating: 4.7,
        reviewCount: 380,
        enrollmentCount: 2900,
        duration: 1200, // 20 hours
        lessons: [
            { id: 'l8-1', courseId: 'sample-8', title: 'Validating Your Idea', description: 'Market research and customer discovery', videoUrl: '', duration: 45, order: 1 },
            { id: 'l8-2', courseId: 'sample-8', title: 'Business Model Canvas', description: 'Designing your business model', videoUrl: '', duration: 50, order: 2 },
            { id: 'l8-3', courseId: 'sample-8', title: 'Building an MVP', description: 'Minimum viable product strategies', videoUrl: '', duration: 55, order: 3 },
            { id: 'l8-4', courseId: 'sample-8', title: 'Fundraising & Pitching', description: 'Investor decks and pitch practice', videoUrl: '', duration: 60, order: 4 },
        ],
        createdAt: new Date('2024-01-10'),
        updatedAt: new Date('2024-05-15'),
    },
    {
        id: 'sample-9',
        title: 'Financial Modeling & Analysis',
        description: 'Build professional financial models in Excel. Cover forecasting, DCF valuation, sensitivity analysis, and scenario modeling. Used by investment bankers and financial analysts worldwide for decision-making.',
        category: 'Business',
        level: 'advanced',
        price: 299,
        instructor: 'inst-9',
        instructorName: 'Jennifer Adams',
        thumbnail: '',
        rating: 4.8,
        reviewCount: 175,
        enrollmentCount: 1500,
        duration: 1560, // 26 hours
        lessons: [
            { id: 'l9-1', courseId: 'sample-9', title: 'Financial Statements', description: 'Income, balance sheet, and cash flow', videoUrl: '', duration: 55, order: 1 },
            { id: 'l9-2', courseId: 'sample-9', title: 'Building a 3-Statement Model', description: 'Linking financial statements', videoUrl: '', duration: 70, order: 2 },
            { id: 'l9-3', courseId: 'sample-9', title: 'DCF Valuation', description: 'Discounted cash flow analysis', videoUrl: '', duration: 65, order: 3 },
        ],
        createdAt: new Date('2024-03-20'),
        updatedAt: new Date('2024-08-05'),
    },
    {
        id: 'sample-10',
        title: 'Project Management Professional',
        description: 'Prepare for PMP certification and master modern project management. Learn Agile, Scrum, Waterfall, risk management, stakeholder communication, and resource planning with hands-on exercises and practice exams.',
        category: 'Business',
        level: 'intermediate',
        price: 199,
        instructor: 'inst-10',
        instructorName: 'Robert Kim',
        thumbnail: '',
        rating: 4.5,
        reviewCount: 520,
        enrollmentCount: 3400,
        duration: 1800, // 30 hours
        lessons: [
            { id: 'l10-1', courseId: 'sample-10', title: 'Project Management Fundamentals', description: 'PMBOK guide overview', videoUrl: '', duration: 45, order: 1 },
            { id: 'l10-2', courseId: 'sample-10', title: 'Agile & Scrum', description: 'Sprints, standups, and retrospectives', videoUrl: '', duration: 55, order: 2 },
            { id: 'l10-3', courseId: 'sample-10', title: 'Risk Management', description: 'Identifying and mitigating risks', videoUrl: '', duration: 50, order: 3 },
        ],
        createdAt: new Date('2024-02-15'),
        updatedAt: new Date('2024-07-20'),
    },

    // ─── Marketing ───
    {
        id: 'sample-11',
        title: 'Digital Marketing Strategy',
        description: 'Develop a complete digital marketing strategy from scratch. Master SEO, content marketing, email campaigns, social media advertising, and analytics. Learn to measure ROI and optimize campaigns for maximum impact.',
        category: 'Marketing',
        level: 'beginner',
        price: 149,
        instructor: 'inst-11',
        instructorName: 'Amanda Brooks',
        thumbnail: '',
        rating: 4.6,
        reviewCount: 445,
        enrollmentCount: 3800,
        duration: 1320, // 22 hours
        lessons: [
            { id: 'l11-1', courseId: 'sample-11', title: 'Marketing Fundamentals', description: 'Channels, funnels, and KPIs', videoUrl: '', duration: 40, order: 1 },
            { id: 'l11-2', courseId: 'sample-11', title: 'SEO Essentials', description: 'On-page, off-page, and technical SEO', videoUrl: '', duration: 55, order: 2 },
            { id: 'l11-3', courseId: 'sample-11', title: 'Social Media Advertising', description: 'Facebook, Instagram, and LinkedIn ads', videoUrl: '', duration: 50, order: 3 },
            { id: 'l11-4', courseId: 'sample-11', title: 'Email Marketing', description: 'Automation, segmentation, and A/B testing', videoUrl: '', duration: 45, order: 4 },
        ],
        createdAt: new Date('2024-01-25'),
        updatedAt: new Date('2024-06-15'),
    },
    {
        id: 'sample-12',
        title: 'Content Marketing & Copywriting',
        description: 'Learn to create content that converts. Master copywriting frameworks (AIDA, PAS), blog strategy, landing page optimization, and content distribution. Build a content calendar and measure engagement effectively.',
        category: 'Marketing',
        level: 'intermediate',
        price: 179,
        instructor: 'inst-12',
        instructorName: 'Daniel Wright',
        thumbnail: '',
        rating: 4.7,
        reviewCount: 210,
        enrollmentCount: 1800,
        duration: 1080, // 18 hours
        lessons: [
            { id: 'l12-1', courseId: 'sample-12', title: 'Copywriting Fundamentals', description: 'AIDA, PAS, and storytelling', videoUrl: '', duration: 45, order: 1 },
            { id: 'l12-2', courseId: 'sample-12', title: 'Blog Strategy', description: 'Topic research and editorial calendar', videoUrl: '', duration: 40, order: 2 },
            { id: 'l12-3', courseId: 'sample-12', title: 'Landing Page Copy', description: 'Headlines, CTAs, and conversions', videoUrl: '', duration: 50, order: 3 },
        ],
        createdAt: new Date('2024-04-01'),
        updatedAt: new Date('2024-08-20'),
    },

    // ─── Data Science ───
    {
        id: 'sample-13',
        title: 'Python for Data Science',
        description: 'Learn Python programming tailored for data analysis. Cover NumPy, Pandas, Matplotlib, and Scikit-learn. Work with real datasets to clean, visualize, and model data. Build a complete data analysis portfolio project.',
        category: 'Data Science',
        level: 'beginner',
        price: 199,
        instructor: 'inst-13',
        instructorName: 'Dr. Priya Sharma',
        thumbnail: '',
        rating: 4.9,
        reviewCount: 620,
        enrollmentCount: 4800,
        duration: 2040, // 34 hours
        lessons: [
            { id: 'l13-1', courseId: 'sample-13', title: 'Python Basics', description: 'Variables, loops, and functions', videoUrl: '', duration: 50, order: 1 },
            { id: 'l13-2', courseId: 'sample-13', title: 'NumPy & Pandas', description: 'Data manipulation and analysis', videoUrl: '', duration: 65, order: 2 },
            { id: 'l13-3', courseId: 'sample-13', title: 'Data Visualization', description: 'Matplotlib and Seaborn charts', videoUrl: '', duration: 55, order: 3 },
            { id: 'l13-4', courseId: 'sample-13', title: 'Machine Learning Basics', description: 'Scikit-learn and model training', videoUrl: '', duration: 70, order: 4 },
        ],
        createdAt: new Date('2023-12-15'),
        updatedAt: new Date('2024-06-30'),
    },
    {
        id: 'sample-14',
        title: 'Machine Learning Engineering',
        description: 'Go beyond tutorials and learn to build production ML systems. Cover feature engineering, model selection, hyperparameter tuning, MLOps, and deploying models with Docker and cloud platforms. Real industry workflows.',
        category: 'Data Science',
        level: 'advanced',
        price: 349,
        instructor: 'inst-14',
        instructorName: 'Dr. James Liu',
        thumbnail: '',
        rating: 4.8,
        reviewCount: 145,
        enrollmentCount: 980,
        duration: 2400, // 40 hours
        lessons: [
            { id: 'l14-1', courseId: 'sample-14', title: 'Feature Engineering', description: 'Transforming raw data into features', videoUrl: '', duration: 60, order: 1 },
            { id: 'l14-2', courseId: 'sample-14', title: 'Model Selection & Tuning', description: 'Cross-validation and grid search', videoUrl: '', duration: 65, order: 2 },
            { id: 'l14-3', courseId: 'sample-14', title: 'MLOps & Deployment', description: 'Docker, CI/CD, and model serving', videoUrl: '', duration: 70, order: 3 },
        ],
        createdAt: new Date('2024-05-01'),
        updatedAt: new Date('2024-09-10'),
    },
    {
        id: 'sample-15',
        title: 'SQL & Database Design',
        description: 'Master SQL from basics to advanced queries. Learn database design, normalization, joins, subqueries, window functions, indexing, and query optimization. Practice with PostgreSQL on real-world datasets.',
        category: 'Data Science',
        level: 'intermediate',
        price: 149,
        instructor: 'inst-15',
        instructorName: 'Kevin Mueller',
        thumbnail: '',
        rating: 4.6,
        reviewCount: 330,
        enrollmentCount: 2600,
        duration: 1320, // 22 hours
        lessons: [
            { id: 'l15-1', courseId: 'sample-15', title: 'SQL Fundamentals', description: 'SELECT, WHERE, and JOIN', videoUrl: '', duration: 45, order: 1 },
            { id: 'l15-2', courseId: 'sample-15', title: 'Advanced Queries', description: 'Subqueries, CTEs, and window functions', videoUrl: '', duration: 55, order: 2 },
            { id: 'l15-3', courseId: 'sample-15', title: 'Database Design', description: 'Normalization and ERD modeling', videoUrl: '', duration: 50, order: 3 },
            { id: 'l15-4', courseId: 'sample-15', title: 'Performance Optimization', description: 'Indexing and query tuning', videoUrl: '', duration: 45, order: 4 },
        ],
        createdAt: new Date('2024-03-10'),
        updatedAt: new Date('2024-07-25'),
    },
    {
        id: 'sample-16',
        title: 'TypeScript Complete Developer Guide',
        description: 'Learn TypeScript from scratch and become a confident developer. Cover type systems, generics, decorators, enums, utility types, and integrating TypeScript with React. Write safer, more maintainable code.',
        category: 'Web Development',
        level: 'intermediate',
        price: 179,
        instructor: 'inst-16',
        instructorName: 'Natalie Green',
        thumbnail: '',
        rating: 4.7,
        reviewCount: 285,
        enrollmentCount: 2200,
        duration: 1500, // 25 hours
        lessons: [
            { id: 'l16-1', courseId: 'sample-16', title: 'TypeScript Basics', description: 'Types, interfaces, and type inference', videoUrl: '', duration: 50, order: 1 },
            { id: 'l16-2', courseId: 'sample-16', title: 'Generics & Utility Types', description: 'Flexible and reusable type patterns', videoUrl: '', duration: 55, order: 2 },
            { id: 'l16-3', courseId: 'sample-16', title: 'TypeScript with React', description: 'Typing components, hooks, and context', videoUrl: '', duration: 60, order: 3 },
        ],
        createdAt: new Date('2024-04-20'),
        updatedAt: new Date('2024-09-01'),
    },
];
